package com.example.csi_dmce.attendance

import android.content.Intent
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.example.csi_dmce.database.*
import kotlinx.coroutines.runBlocking

class AttendanceActivity: AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        runBlocking {
            val studentID:String = intent.getStringExtra("student_id").toString()
            //where to get the eventID from?
            // val eventId : String = intent.getStringExtra("event_id").toString()

            val eventId: String = "DCF-1004207400"
            val eventUUID: String =  runBlocking  { EventWrapper.getEventUUID(eventId)!!}

            //when scan button is clicked
            val intent = Intent(applicationContext, scanQrActivity::class.java)
            startActivity(intent)

            val qrContents:String = intent.getStringExtra("QR_contents").toString()
            val qrOrder : String = qrContents.split("_").toString()

            if(qrContents!=null){
                //compare these contents to the ones from the QR generated by admin class
                val eventUuid = EventWrapper.getEventUUID(eventId).toString()
                if(qrContents[1].toString() == eventUuid){
                    when(qrOrder){
                        "FIRST"-> AttendanceWrapper.setQRAttendance(studentID, eventUUID, "first", true)
                        "SECOND"-> AttendanceWrapper.setQRAttendance(studentID, eventUUID, "second", true)
                        else -> return@runBlocking
                    }
                }
            }
            val attendanceObject = AttendanceWrapper.getAttendanceObject(studentID, eventUUID)
            val first : Boolean = attendanceObject?.first!!
            val second : Boolean = attendanceObject?.second!!

            if(first==true && second==true){
                val studentObj : Student = StudentWrapper.getStudent(studentID)!!
                val eventObj: Event =  EventWrapper.getEvent(eventId)!!
                CommonWrapper.addAttendee(eventObj, studentObj)
            }
        }
    }
}